{% set data = load_setup_py_data() %}

package:
  name: pymesh
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/PyMesh/PyMesh.git
  git_rev: master


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python=3.7
    - pip
    - scipy
    - numpy
    - nose
    - gmp=6.1.2
    - mpfr=4.0.1
    - boost=1.67.0

  run:
    - "python>=3"
    - numpy
    - boost=1.67.0
    - "mpfr>=4"

